# .gitlab-ci.yml
image: node:14.8.0

stages:
  - install_dependencies
  - build
  - test



install_dependencies:
  stage: install_dependencies
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - yarn install
  only:
    changes:
      - yarn.lock

      

#continuous integration
e2e-test:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - build/
    policy: pull
  services:
    - mongo
  script:
    yarn test